model_config.yaml

model:
  type: "transformer_lstm_hybrid"
  architecture:
    embedding_dim: 128
    hidden_dim: 256
    num_layers: 3
    dropout_rate: 0.3

  input_features:
    - price_history
    - technical_indicators
    - sentiment_score
    - volume
    - market_index

  sequence_length: 60
  prediction_horizon: 7

training:
  batch_size: 64
  learning_rate: 0.0001
  epochs: 100
  optimizer: "adam"
  loss_function: "mse"
  early_stopping:
    patience: 10
    min_delta: 0.0001

hardware:
  gpu:
    name: "NVIDIA RTX 4060 TI"
    memory: 16
    precision: "float16"

regularization:
  l1_lambda: 0.0001
  l2_lambda: 0.0002

data_preprocessing:
  normalization: "min_max"
  scaling_method: "robust_scaler"
  time_series_augmentation: true

hyperparameter_tuning:
  strategy: "bayesian_optimization"
  max_trials: 50
  search_space:
    learning_rate: [0.00001, 0.001]
    hidden_dim: [128, 512]
    num_layers: [2, 4]