name: Run Uploaded Python File

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true
        pip install matplotlib pandas scikit-learn

    - name: Run your script
      run: |
        python main.py

    - name: Upload all result files
      uses: actions/upload-artifact@v4
      with:
        name: result-files
        path: |
          *.png
          *.jpg
          *.jpeg
          *.pdf
          *.csv
          *.txt
