name: Run Uploaded Python File

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  run-script:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true  # 可选
        pip install matplotlib  # 或其他你用到的绘图库
        pip install pandas
        pip install scikit-learn

    - name: Run your script
      run: |
        python main.py  # 替换为你的脚本名称

    - name: Upload result image
      uses: actions/upload-artifact@v4
      with:
        name: result-image
        path: predicted_price.png  # 确保脚本输出图像名为 result.png
